processor:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3002:3002"
  external_links:
    - champaignakprocessor_db_1
  environment:
    PG_USERNAME: postgres
    PG_HOST: champaignakprocessor_db_1

  command: bundle exec shoryuken -R -C config/shoryuken.yml

db:
  image: postgres
  ports:
    - "5432"
  environment:
      POSTGRES_DB: champaign_test