processor:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  external_links:
    - champaign_db_1
  environment:
    PG_USERNAME: postgres
    PG_HOST: champaign_db_1

db:
  image: postgres
  ports:
    - "5432"
  environment:
      POSTGRES_DB: champaign_test