version: 2

defaults: &defaults
  working_directory: ~/circleci-champaign-ak-processor
  docker:
    - image: soutech/ruby:2.6-stretch-node-awscli

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restoring bundler cache
          key: gem-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: bundle install --jobs 4 --deployment
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
            - .bundle

  rspec:
    docker:
      - image: soutech/ruby:2.6-stretch-node-awscli
        environment:
          PG_USERNAME: champaign
          PG_PASSWORD: champaign
          RAILS_ENV: test
          AK_HOST: https://act.sumofus.org/rest/v1
          AK_USERNAME: ak_username
          AK_PASSWORD: ak_password
          HPC_RULE_ID: 22
          AK_SUBSCRIPTION_PAGE_EN: 'registration'
          AK_SUBSCRIPTION_PAGE_DE: 'registration_german'
          AK_SUBSCRIPTION_PAGE_FR: 'registration_french'
          AWS_REGION: us-west-2
          CONSTITUENCIES_TABLE: UkConstituencies
      - image: circleci/postgres:9.4-alpine-ram
        environment:
          POSTGRES_USER: champaign
          POSTGRES_DB: champaign_test
      - image: redis
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign-ak-processor
      - run:
          name: Bundler
          command: bundle --path vendor/bundle
      - run:
          name: Run specs
          command: bundle exec rspec spec

  build_docker_image:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign-ak-processor
      - setup_remote_docker
      - run:
          name: Docker build
          command: .circleci/build.sh

  deploy_production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign-ak-processor
      - run:
          name: Deploy production
          command: .circleci/deploy.sh $CIRCLE_SHA1 'champaign' 'ak-worker-production' 'logs3.papertrailapp.com:44107'

  deploy_staging:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-champaign-ak-processor
      - run:
          name: Deploy staging
          command: .circleci/deploy.sh $CIRCLE_SHA1 'champaign' 'ak-worker-staging' 'logs3.papertrailapp.com:34848'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies

      - rspec:
          requires:
            - install_dependencies

      - build_docker_image:
          filters:
            branches:
              only:
                - master
                - development
                - /^feature(?:\/|-|\.).+$/

      - deploy_production:
          requires:
            - build_docker_image
            - rspec
          filters:
            branches:
              only:
                - master

      - deploy_staging:
          requires:
            - build_docker_image
            - rspec
          filters:
            branches:
              only:
                - development
