processor:
  image: "soutech/champaign-ak-processor:$CIRCLE_SHA1"
  links:
    - db
    - redis
  command: /myapp/.circleci/run-tests
  env_file:
    - test.env

db:
  image: postgres
  ports:
    - "5432"
  environment:
    POSTGRES_DB: champaign_test
redis:
  image: redis
  command: redis-server --protected-mode no
